Portfolio/Models/JuliaImage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Web;

namespace Portfolio.Models
{
    public class JuliaImage
    {
        //Takes this to page
        public string FilePath { get; set; }



        //Returns this to Controller on Form submit

        public float ConstantReal { get; set; } = -0.221f;
        public float ConstantImaginary { get; set; } = -0.713f;
        public float Threshold { get; set; } = 2f;
        public float GreenDivider { get; set; } = 1;
        public float BlueDivider { get; set; } = 1;
        public float RedDivider { get; set; } = 1;
        public float AlphaDivider { get; set; } = 1;
        public int Steps { get; set; } = 255;
        public int Width { get; set; } = 500;
        public int Height { get; set; } = 500;


        public Complex Constant { get; set; }
    }
}

Portfolio/Controllers/FractalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Numerics;
using System.Drawing;
using System.Drawing.Imaging;
using System.Threading.Tasks;
using System.Runtime.InteropServices;
using System.IO;
using Portfolio.Models;

namespace Portfolio.Controllers
{
    public class FractalController : Controller
    {



        public ActionResult Index(JuliaImage myModel)
        {

            Dictionary<Tuple<int, int>, int> xypos = new Dictionary<Tuple<int, int>, int>();

            //Clean up folder if its size is greater then a 1gb
            var filesInPath = Directory.GetFiles(System.Configuration.ConfigurationManager.AppSettings["ImageDirectory"], "*.*");
            long directorySize = 0;
            foreach (string name in filesInPath)
            {
                FileInfo info = new FileInfo(name);
                directorySize += info.Length;
            }
            //Rough estimate cant remember if its bytes or bits atm
            if (directorySize > 1 * 1000 * 1000 * 1000)
            {

                foreach (string name in filesInPath)
                {
                    try
                    {
                        System.IO.File.Delete(name);
                    }
                    catch//(Exception ex) //Supress and pass on
                    {

                    }
                }
            }



            //These shouldnt happen
            if (myModel == null)
            {
                myModel = new JuliaImage();
            }
            if (myModel.AlphaDivider <= 0)
            {
                myModel.AlphaDivider = 1;
            }
            if (myModel.RedDivider <= 0)
            {
                myModel.RedDivider = 1;
            }
            if (myModel.GreenDivider <= 0)
            {
                myModel.GreenDivider = 1;
            }
            if (myModel.BlueDivider <= 0)
            {
                myModel.BlueDivider = 1;
            }
            if (myModel.Steps <= 0 || myModel.Steps > 255)
            {
                myModel.Steps = 255;
            }
            if (myModel.Height <= 0)
            {
                myModel.Height = 500;
            }
            if (myModel.Width <= 0)
            {
                myModel.Width = 500;
            }

            //Init Constant
            myModel.Constant = new Complex(myModel.ConstantReal, myModel.ConstantImaginary);



            float height = myModel.Height;
            float width = myModel.Width;

            for (int i = 0; i <= width; i++)
            {
                for (int j = 0; j <= height; j++)
                {
                    var result = CalculateVals(new Complex(i * 2 / width - 1, j * 2 / height - 1), ref myModel);
                    xypos.Add(new Tuple<int, int>(i, j), result);
                }
            }


            Guid fileName = Guid.NewGuid();
            using (Bitmap bmp = new Bitmap(Convert.ToInt32(width), Convert.ToInt32(height)))
            {
                using (Graphics g = Graphics.FromImage(bmp))
                {
                    for (int x = 0; x <= width; x++)
                    {
                        for (int y = 0; y <= height; y++)
                        {
                            int value = xypos[new Tuple<int, int>(x, y)];
                            int av = Convert.ToInt32(value / myModel.AlphaDivider);
                            int rv = Convert.ToInt32(value / myModel.RedDivider);
                            int gv = Convert.ToInt32(value / myModel.GreenDivider);
                            int bv = Convert.ToInt32(value / myModel.BlueDivider);
                            if (av < 0 || av > 255)
                            {
                                av = 255;
                            }
                            if (rv < 0 || rv > 255)
                            {
                                rv = 255;
                            }
                            if (gv < 0 || gv > 255)
                            {
                                gv = 255;
                            }
                            if (bv < 0 || bv > 255)
                            {
                                bv = 255;
                            }
                            g.FillRectangle(new SolidBrush(
                                Color.FromArgb(
                                    av, rv, gv, bv
                                    )), new Rectangle(x, y, 1, 1));
                        }
                    }
                }
                bmp.Save(System.Configuration.ConfigurationManager.AppSettings["ImageDirectory"] + fileName.ToString() + ".png", ImageFormat.Png);
            }
            myModel.FilePath = "/Fractal/ImageResource/" + fileName.ToString();
            return View(myModel);
        }




        public int CalculateVals(Complex val, ref JuliaImage myModel)
        {
            int steps = 0;
            Complex newCmp = val;
            double magnitude = 0;
            while (magnitude < myModel.Threshold && steps < myModel.Steps)
            {
                steps++;
                var tempReal = (newCmp * newCmp) + myModel.Constant;
                magnitude = tempReal.Magnitude;
                newCmp = tempReal;
            }

            return steps;
        }





        public ActionResult ImageResource(string id)
        {
            try
            {
                //id has to = a guid
                var testGuidParse = Guid.Parse(id);
                var dir = System.Configuration.ConfigurationManager.AppSettings["ImageDirectory"];
                var path = Path.Combine(dir, id + ".png"); //validate the path for security or use other means to generate the path.
                return base.File(path, "image/png");
            }
            catch
            {
                return View("");
            }
        }








    }
}

Portfolio/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portfolio.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {






            return View();
        }



        public ActionResult Experience()
        {


            return View();
        }


        public ActionResult Robots()
        {
            Response.ContentType = "text/plain";
            return View();
        }

    }
}

Portfolio/Views/Fractal/Index.cshtml
@using System.Drawing
@model Portfolio.Models.JuliaImage

@{
    ViewBag.Title = "Julia Render";
}

<h2>Fractal</h2>



@using (Html.BeginForm("Index", "Fractal"))
{
    <div class="formdiv">
        <div>
            @Html.LabelFor(m => m.Width)
            @Html.TextBoxFor(m => m.Width, new { @class = "form-control" })
            @Html.LabelFor(m => m.Height)
            @Html.TextBoxFor(m => m.Height, new { @class = "form-control" })
        </div>

        <div>

            @Html.LabelFor(m => m.ConstantReal)
            @Html.TextBoxFor(m => m.ConstantReal, new { @class = "form-control" })
            @Html.LabelFor(m => m.ConstantImaginary)
            @Html.TextBoxFor(m => m.ConstantImaginary, new { @class = "form-control" })
        </div>
        <div>
            @Html.LabelFor(m => m.Threshold)
            @Html.TextBoxFor(m => m.Threshold, new { @class = "form-control" })
            @Html.LabelFor(m => m.Steps)
            @Html.TextBoxFor(m => m.Steps, new { @class = "form-control" })

        </div>

        <div>
            @Html.LabelFor(m => m.AlphaDivider)
            @Html.TextBoxFor(m => m.AlphaDivider, new { @class = "form-control" })
            @Html.LabelFor(m => m.RedDivider)
            @Html.TextBoxFor(m => m.RedDivider, new { @class = "form-control" })
        </div>
        <div>
            @Html.LabelFor(m => m.GreenDivider)
            @Html.TextBoxFor(m => m.GreenDivider, new { @class = "form-control" })
            @Html.LabelFor(m => m.BlueDivider)
            @Html.TextBoxFor(m => m.BlueDivider, new { @class = "form-control" })
        </div>

        <input type="submit" value="Submit" />
    </div>
}



<img src="@Model.FilePath" width="@Model.Width" height="@Model.Height" />


@section metabundle{
    <meta name="description" content="Matthew Worthley -> Julia Fractal">
}

Portfolio/Views/Home/Experience.cshtml
@{
    ViewBag.Title = "Experience";
}





<h2>Qualifications</h2>
<ul>
    <li>Bachelor of Information Technology (University of Canberra)</li>
</ul>
<h2>Experience</h2>
<ul>
    <li>
        1/3/2015 – Present
        <div>
            Company: Managed Business IT Solutions (MBITS)
            <br />
            Position: Software Developer
            <br />
            Type: Full Time
            <br />
            Working for MBITS I have worked upon many environments such as C# applications designed for servers and clients.
            Also developed for C# ASP.Net MVC web pages for windows environments.
            I have worked upon inhouse systems and off the shelf software for large clients.
            Database architectures I've worked upon have been MSSQL, MYSQL and CQL
        </div>
    </li>

    <li>
        1/8/2014 – 17/10/2014
        <div>
            Company: Evolution Stainless Steel
            <br />
            Position: Labourer
            <br />
            Type: Contract
            <br />
            Whilst working for Evolution Stainless Steel the duties I was tasked for was to perform site measurements and liaise with clients and draw up projects that my team will then fabricate and install for them.
        </div>
    </li>

    <li>
        1/8/2014 – 17/10/2014
        <div>
            Company: Capital Engineering
            <br />
            Position: Trade Assistant
            <br />
            Type: Full Time
            <br />
            Performed the duties of an assistant for my father’s family business where the duties I performed consisted of the recording of site measurements, fabrication and installation of steel structures and customer liaison.
            <br />

            Qualifications obtained:
            <ul>
                <li>
                    Industry white card
                </li>
                <li>
                    Apply first aid certificate
                </li>
                <li>
                    Working at heights certificate
                </li>
                <li>
                    Confined space certificate
                </li>
                <li>
                    Gas testing certificate
                </li>
            </ul>
        </div>
    </li>
</ul>


@section metabundle{
<meta name="description" content="Matthew Worthley -> Work Experience History">
}

Portfolio/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div itemscope itemtype="http://data-vocabulary.org/Person">
    <h2>About Me</h2>
    <span>
        I'm <span itemprop="name">Matthew Worthley</span>, an aspiring software developer and tech enthusiast.
    </span>
    <h3>Languages</h3>
    <ul>
        <li>C#</li>
        <li>C++</li>
        <li>Java</li>
    </ul>
    <h3>Web Dev</h3>
    <ul>
        <li>PHP</li>
        <li>C# ASP.net</li>
        <li>JS</li>
    </ul>
    <h3>Database Architectures</h3>
    <ul>
        <li>MSSQL</li>
        <li>MYSQL</li>
        <li>CQL</li>
    </ul>
    <h3>Environments</h3>
    <ul>
        <li>Windows (ME, XP, 7, 8, 10, 2008 R2, 2012)</li>
        <li>Linux (Ubuntu, BackTrack/Kali, Fedora)</li>
        <li>FreeBSD</li>
    </ul>
</div>

@section metabundle{
    <meta name="description" content="Matthew Worthley -> About me">
}

Portfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />


    @RenderSection("metabundle", false)

    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>Matthew Worthley - @ViewBag.Title</title>
    @Styles.Render("~/Styles/css")
    @Scripts.Render("~/Scripts/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    @*<span class="icon-bar"></span>*@
                    @*<span class="icon-bar"></span>*@
                </button>
                @Html.ActionLink("Matthew Worthley - Portfolio", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Experience", "Experience", "Home")</li>
                    <li>@Html.ActionLink("Fractal", "Index", "Fractal")</li>
                    <li><a href="https://github.com/ZeroPoints" target="_blank">GitHub</a></li>
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>


    <footer>
        <div>
            <p>@DateTime.Now.Year</p>
        </div>
    </footer>

    @Scripts.Render("~/Scripts/jquery")
    @Scripts.Render("~/Scripts/bootstrap")
    @RenderSection("scripts", false)
</body>
</html>